sever:
  port: 8080
spring:
  application:
    name: basicwear
  datasource:
    url : jdbc:postgresql://localhost:5432/shop
    username : postgres
    password : 1004
  jpa:
    hibernate:
      ddl-auto : update
    show-sql : true