server:
  port: 8080
spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: 1004
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: 1234